// utils/korean-tickers.js
// S&P500, NASDAQ100, 기타 주요 인기 종목 및 ETF 한글-티커 매핑
const KOREAN_TICKER_MAP = {
    // ---- 인기 급등 기술/크립토/그로스 ----
    '아이렌': { ticker: 'IREN', name: 'Iris Energy' },
    '아이리스에너지': { ticker: 'IREN', name: 'Iris Energy' },
    '클린스파크': { ticker: 'CLSK', name: 'CleanSpark' },
    '마라톤': { ticker: 'MARA', name: 'Marathon Digital' },
    '마라톤디지털': { ticker: 'MARA', name: 'Marathon Digital' },
    '라이엇': { ticker: 'RIOT', name: 'Riot Platforms' },
    '아이온큐': { ticker: 'IONQ', name: 'IonQ' },
    '사운드하운드': { ticker: 'SOUN', name: 'SoundHound AI' },
    '소파이': { ticker: 'SOFI', name: 'SoFi Technologies' },
    '업스타트': { ticker: 'UPST', name: 'Upstart' },
    '어펌': { ticker: 'AFRM', name: 'Affirm' },
    '코인베이스': { ticker: 'COIN', name: 'Coinbase' },
    '로블록스': { ticker: 'RBLX', name: 'Roblox' },
    '스냅': { ticker: 'SNAP', name: 'Snap Inc.' },
    '레딧': { ticker: 'RDDT', name: 'Reddit' },
    '리비안': { ticker: 'RIVN', name: 'Rivian' },
    '루시드': { ticker: 'LCID', name: 'Lucid' },
    '니오': { ticker: 'NIO', name: 'NIO' },
    '샤오펑': { ticker: 'XPEV', name: 'XPeng' },
    '리오토': { ticker: 'LI', name: 'Li Auto' },
    
    // ---- 반도체/AI/하드웨어 ----
    '엔비디아': { ticker: 'NVDA', name: 'NVIDIA' },
    '암': { ticker: 'ARM', name: 'Arm Holdings' },
    '에이엠디': { ticker: 'AMD', name: 'AMD' },
    '마이크론': { ticker: 'MU', name: 'Micron' },
    '인텔': { ticker: 'INTC', name: 'Intel' },
    '브로드컴': { ticker: 'AVGO', name: 'Broadcom' },
    '티에스엠씨': { ticker: 'TSM', name: 'TSMC' },
    '타이완반도체': { ticker: 'TSM', name: 'TSM' },
    '대만반도체': { ticker: 'TSM', name: 'TSM' },
    '퀄컴': { ticker: 'QCOM', name: 'Qualcomm' },
    '텍사스인스트루먼트': { ticker: 'TXN', name: 'Texas Instruments' },
    '어플라이드머티어리얼즈': { ticker: 'AMAT', name: 'Applied Materials' },
    '램리서치': { ticker: 'LRCX', name: 'Lam Research' },
    '에이에스엠엘': { ticker: 'ASML', name: 'ASML' },
    '마벨': { ticker: 'MRVL', name: 'Marvell' },
    '아나로그디바이스': { ticker: 'ADI', name: 'Analog Devices' },
    '엔엑스피': { ticker: 'NXPI', name: 'NXP Semiconductors' },
    '케이엘에이': { ticker: 'KLAC', name: 'KLA Corporation' },
    '마이크로칩': { ticker: 'MCHP', name: 'Microchip' },
    '슈퍼마이크로': { ticker: 'SMCI', name: 'Super Micro Computer' },
    '슈퍼마이크로컴퓨터': { ticker: 'SMCI', name: 'Super Micro Computer' },
    '델': { ticker: 'DELL', name: 'Dell Technologies' },
    '에이치피': { ticker: 'HPQ', name: 'HP Inc.' },
    
    // ---- 빅테크/소프트웨어 ----
    '애플': { ticker: 'AAPL', name: 'Apple' },
    '마이크로소프트': { ticker: 'MSFT', name: 'Microsoft' },
    '알파벳': { ticker: 'GOOGL', name: 'Alphabet' },
    '구글': { ticker: 'GOOGL', name: 'Alphabet' },
    '아마존': { ticker: 'AMZN', name: 'Amazon' },
    '메타': { ticker: 'META', name: 'Meta Platforms' },
    '페이스북': { ticker: 'META', name: 'Meta' },
    '오라클': { ticker: 'ORCL', name: 'Oracle' },
    '어도비': { ticker: 'ADBE', name: 'Adobe' },
    '세일즈포스': { ticker: 'CRM', name: 'Salesforce' },
    '서비스나우': { ticker: 'NOW', name: 'ServiceNow' },
    '크라우드스트라이크': { ticker: 'CRWD', name: 'CrowdStrike' },
    '팔로알토': { ticker: 'PANW', name: 'Palo Alto Networks' },
    '스노우플레이크': { ticker: 'SNOW', name: 'Snowflake' },
    '데이터독': { ticker: 'DDOG', name: 'Datadog' },
    '몽고디비': { ticker: 'MDB', name: 'MongoDB' },
    '포티넷': { ticker: 'FTNT', name: 'Fortinet' },
    '클라우드플레어': { ticker: 'NET', name: 'Cloudflare' },
    '줌': { ticker: 'ZM', name: 'Zoom' },
    '아틀라시안': { ticker: 'TEAM', name: 'Atlassian' },
    '워크데이': { ticker: 'WDAY', name: 'Workday' },
    '스포티파이': { ticker: 'SPOT', name: 'Spotify' },
    '쇼피파이': { ticker: 'SHOP', name: 'Shopify' },
    '넷플릭스': { ticker: 'NFLX', name: 'Netflix' },
    '우버': { ticker: 'UBER', name: 'Uber' },
    '에어비앤비': { ticker: 'ABNB', name: 'Airbnb' },
    '도어대시': { ticker: 'DASH', name: 'DoorDash' },
    
    // ---- 의료/제약/헬스케어 ----
    '일라이릴리': { ticker: 'LLY', name: 'Eli Lilly' },
    '노보노디스크': { ticker: 'NVO', name: 'Novo Nordisk' },
    '유나이티드헬스': { ticker: 'UNH', name: 'UnitedHealth' },
    '존슨앤존슨': { ticker: 'JNJ', name: 'Johnson & Johnson' },
    '애비': { ticker: 'ABBV', name: 'AbbVie' },
    '머크': { ticker: 'MRK', name: 'Merck' },
    '화이자': { ticker: 'PFE', name: 'Pfizer' },
    '서모피셔': { ticker: 'TMO', name: 'Thermo Fisher' },
    '애보트': { ticker: 'ABT', name: 'Abbott Laboratories' },
    '암젠': { ticker: 'AMGN', name: 'Amgen' },
    '모더나': { ticker: 'MRNA', name: 'Moderna' },
    '길리어드': { ticker: 'GILD', name: 'Gilead Sciences' },
    '다나허': { ticker: 'DHR', name: 'Danaher' },
    '인튜이티브': { ticker: 'ISRG', name: 'Intuitive Surgical' },
    '인튜이티브서지컬': { ticker: 'ISRG', name: 'Intuitive Surgical' },
    
    // ---- 금융/소비재/기타 ----
    '테슬라': { ticker: 'TSLA', name: 'Tesla' },
    '비자': { ticker: 'V', name: 'Visa' },
    '마스터카드': { ticker: 'MA', name: 'Mastercard' },
    '제이피모간': { ticker: 'JPM', name: 'JPMorgan Chase' },
    '버크셔해서웨이': { ticker: 'BRK.B', name: 'Berkshire Hathaway' },
    '버크셔': { ticker: 'BRK.B', name: 'Berkshire Hathaway' },
    '뱅크오브아메리카': { ticker: 'BAC', name: 'Bank of America' },
    '엑슨모빌': { ticker: 'XOM', name: 'Exxon Mobil' },
    '엑슨': { ticker: 'XOM', name: 'Exxon Mobil' },
    '셰브런': { ticker: 'CVX', name: 'Chevron' },
    '월마트': { ticker: 'WMT', name: 'Walmart' },
    '코스트코': { ticker: 'COST', name: 'Costco' },
    '홈디포': { ticker: 'HD', name: 'Home Depot' },
    '프록터앤갬블': { ticker: 'PG', name: 'Procter & Gamble' },
    '피앤지': { ticker: 'PG', name: 'Procter & Gamble' },
    '스타벅스': { ticker: 'SBUX', name: 'Starbucks' },
    '맥도날드': { ticker: 'MCD', name: 'McDonald\'s' },
    '코카콜라': { ticker: 'KO', name: 'Coca-Cola' },
    '펩시': { ticker: 'PEP', name: 'PepsiCo' },
    '월트디즈니': { ticker: 'DIS', name: 'Disney' },
    '디즈니': { ticker: 'DIS', name: 'Disney' },
    '보잉': { ticker: 'BA', name: 'Boeing' },
    '블랙록': { ticker: 'BLK', name: 'BlackRock' },
    '모건스탠리': { ticker: 'MS', name: 'Morgan Stanley' },
    
    // ---- 레버리지 / 인버스 / 주요 ETF (한글 발음) ----
    '티큐': { ticker: 'TQQQ', name: 'TQQQ' },
    '속슬': { ticker: 'SOXL', name: 'SOXL' },
    '스파이': { ticker: 'SPY', name: 'SPY' },
    '스파이기': { ticker: 'SPYG', name: 'SPYG' },
    '콜드': { ticker: 'BOIL', name: 'BOIL' },
    '숏큐': { ticker: 'SQQQ', name: 'SQQQ' },
    '큐큐큐': { ticker: 'QQQ', name: 'QQQ' },
    '에센피': { ticker: 'SPY', name: 'SPY' },
    '나스닥': { ticker: 'QQQ', name: 'QQQ' },
    
    // ---- 한국(추가발음) ----
    '투루엔': { ticker: '417790', name: '투루엔', market: 'KR', corpCode: null },
    '삼전': { ticker: '005930', name: '삼성전자', market: 'KR', corpCode: '00126380' },
};

module.exports = { KOREAN_TICKER_MAP };
